# Source: cluster-api-aws/templates/machine-pool.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: c362106i7-mp-taco
  namespace: c362106i7
spec:
  eksNodegroupName: c362106i7-mp-taco
  instanceType: t3.2xlarge
  diskSize: 200
  scaling:
    maxSize: 16
    minSize: 1
  remoteAccess:
    sshKeyName: tks-seoul
